CREATE DATABASE IF NOT EXISTS compta CHARSET utf8mb4 COLLATE utf8mb4_general_ci;
USE compta;

CREATE TABLE IF NOT EXISTS ARTICLES (
    id INT PRIMARY KEY NOT NULL,
    ref VARCHAR(50),
    designation VARCHAR(100),
    prix DECIMAL(6 , 2 ),
    id_fou INT
);

CREATE TABLE IF NOT EXISTS FOURNISSEUR (
    id INT PRIMARY KEY,
    nom VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS BON (
    id INT PRIMARY KEY,
    numero INT,
    date_cmde TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    delai INT,
    id_fou INT
);
CREATE TABLE IF NOT EXISTS COMPO (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    qte INT,
    CONSTRAINT fk_numArticle FOREIGN KEY (id)
        REFERENCES ARTICLES (id)
);
